apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.name }}
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: {{ .Values.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
    spec:
      initContainers:
        - name: {{ .Values.application.name }}-init
          image:  "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          env:
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: database-url-secret
                  key: DATABASE_URL 
          command: ["npx", "prisma", "migrate", "deploy"]
      containers:
        - name: {{ .Values.application.name }}
          image:  "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.port | default 1991 }}
          env:
            - name: "PORT"
              value: {{ (.Values.port | default 1991) | quote }}
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: database-url-secret
                  key: DATABASE_URL

          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu}}
              memory: {{ .Values.resources.limits.memory}}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory}}