apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.application.name }}-service
  namespace: {{ .Values.application.name }}
spec:
  selector: 
    app: {{ .Values.application.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1991
