apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.name }}
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: {{ .Values.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
    spec:
      containers:
        - name: {{ .Values.application.name }}
          image:  "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu}}
              memory: {{ .Values.resources.limits.memory}}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory}}
          env:
          - name: NGINX_HOSTNAME
            value: {{ .Values.host | default "localhost"}}