apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: progress-tracker-ingress
  namespace:  {{ .Values.application.name }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.application.name }}-ingress-stripprefix@kubernetescrd
spec:
  rules:
    - host: {{ .Values.host | default "localhost"}}
      http:
        paths:
         - path: /tracker
           pathType: Prefix
           backend:
            service:
              name: {{ .Values.application.name }}-service
              port:
                number: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ingress-stripprefix
  namespace: {{ .Values.application.name }}
spec:
  stripPrefix:
    prefixes:
      - /tracker