apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Namespace }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector: 
    app: {{ .Release.Namespace }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
