apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: {{ .Values.application.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-config
  namespace: {{ .Values.application.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
