apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pi-home-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.host | default "localhost"}}
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
            service:
              name: {{ .Values.application.name }}-service
              port:
                number: 80