apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.application.name }}-service
  namespace: {{ .Values.application.name }}
spec:
  type: ClusterIP # ClusterIP is the default https://kubernetes.io/docs/concepts/services-networking/service/#type-clusterip
  selector: 
    app: {{ .Values.application.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
